This uses Docker Compose to run the Kafka Connect worker.

1. Bring the Docker Compose up
+
[source,bash]
----
docker-compose up -d
----

2. Make sure everything is up and running
+
[source,bash]
----
➜ docker-compose ps
     Name                    Command                  State                     Ports
---------------------------------------------------------------------------------------------------
broker            /etc/confluent/docker/run        Up             0.0.0.0:9092->9092/tcp
kafka-connect     bash -c cd /usr/share/conf ...   Up (healthy)   0.0.0.0:8083->8083/tcp, 9092/tcp
kafkacat          /bin/sh -c apk add jq;           Up
                  wh ...
ksqldb            /usr/bin/docker/run              Up             0.0.0.0:8088->8088/tcp
mysql             docker-entrypoint.sh mysqld      Up             0.0.0.0:3306->3306/tcp, 33060/tcp
schema-registry   /etc/confluent/docker/run        Up             0.0.0.0:8081->8081/tcp
zookeeper         /etc/confluent/docker/run        Up             2181/tcp, 2888/tcp, 3888/tcp
----

3. Create test topics + data using ksqlDB (but it's still just a Kafka topic under the covers)

[source,bash]
----
docker exec -it ksqldb ksql http://ksqldb:8088
----

[source,sql]
----
CREATE STREAM dim_sensores (KEY_COL VARCHAR KEY, id_sensor INT, nombre_sensor VARCHAR)
  WITH (KAFKA_TOPIC='dim_sensores', PARTITIONS=1, VALUE_FORMAT='AVRO');
----

[source,sql]
----
INSERT INTO dim_sensores (KEY_COL, id_sensor, nombre_sensor) VALUES ('X',1,'sensor 1');
INSERT INTO dim_sensores (KEY_COL, id_sensor, nombre_sensor) VALUES ('Y',2,'sensor 2');
----

[source,sql]
----
SHOW TOPICS;
PRINT dim_sensores FROM BEGINNING LIMIT 2;
----

[source,sql]
----
Key format: KAFKA_STRING
Value format: AVRO or KAFKA_STRING
rowtime: 2026/04/02 16:16:35.392 Z, key: X, value: {"ID_SENSOR": 1, "NOMBRE_SENSOR": "sensor 1"}, partition: 0
rowtime: 2026/04/02 16:16:35.441 Z, key: Y, value: {"ID_SENSOR": 2, "NOMBRE_SENSOR": "sensor 2"}, partition: 0
Topic printing ceased
----

Now topic of readings:

[source,sql]
----
CREATE STREAM readings (KEY_COL VARCHAR KEY, id_sensor INT, value INT)
  WITH (KAFKA_TOPIC='readings', PARTITIONS=1, VALUE_FORMAT='AVRO');
----

[source,sql]
---
INSERT INTO readings (KEY_COL, id_sensor, value) VALUES ('X',1,1100);
INSERT INTO readings (KEY_COL, id_sensor, value) VALUES ('Y',2,2000);
----

[source,sql]
----
SHOW TOPICS;
PRINT readings FROM BEGINNING LIMIT 2;
----

[source,sql]
----
Key format: KAFKA_STRING
Value format: AVRO
rowtime: 2026/04/02 16:24:11.151 Z, key: X, value: {"ID_SENSOR": 1, "VALUE": 1100}, partition: 0
rowtime: 2026/04/02 16:24:11.194 Z, key: Y, value: {"ID_SENSOR": 2, "VALUE": 2000}, partition: 0
Topic printing ceased
----

Now a topic joinning de readings with dim_sensors:

First, make a test:

[source,sql]
----
SELECT
    T0.id_sensor ROWKEY, -- KEY
    T1.id_sensor as id,
    T1.nombre_sensor as name,
    T0.value as value
    FROM readings T0
    INNER JOIN dim_sensores T1 WITHIN 3 DAYS
    ON T0.id_sensor = T1.id_sensor
EMIT CHANGES;
----

[source,bash]
----
+------------------+------------------+------------------+------------------+
|ROWKEY            |ID                |NAME              |VALUE             |
+------------------+------------------+------------------+------------------+
|1                 |1                 |sensor 1          |1100              |
|2                 |2                 |sensor 2          |2000              |
----

Evething ok?, create new stream/topic enrich

[source,sql]
----
CREATE STREAM IF NOT EXISTS reading_enrich WITH (KAFKA_TOPIC='reading_enrich', PARTITIONS=1, REPLICAS=1, VALUE_FORMAT='AVRO') 
AS SELECT
    T0.id_sensor ROWKEY, -- KEY
    T1.id_sensor as id,
    T1.nombre_sensor as name,
    T0.value as value
    FROM readings T0
    INNER JOIN dim_sensores T1 WITHIN 3 DAYS
    ON T0.id_sensor = T1.id_sensor
;
----

Check new Topic:
[source,sql]
----
SHOW TOPICS;
PRINT reading_enrich FROM BEGINNING LIMIT 2;
----

[source,sql]
----
Key format: KAFKA_INT or KAFKA_STRING
Value format: AVRO
rowtime: 2026/04/02 16:24:11.151 Z, key: 1, value: {"ID": 1, "NAME": "sensor 1", "VALUE": 1100}, partition: 0
rowtime: 2026/04/02 16:24:11.194 Z, key: 2, value: {"ID": 2, "NAME": "sensor 2", "VALUE": 2000}, partition: 0
Topic printing ceased
----

Try with a new incoming reading from sensor 2.

[source,sql]
---
INSERT INTO readings (KEY_COL, id_sensor, value) VALUES ('4',2,9999);
----

[source,sql]
----
PRINT reading_enrich FROM BEGINNING LIMIT 10;
----

[source,sql]
----
Key format: KAFKA_INT or KAFKA_STRING
Value format: AVRO
rowtime: 2026/04/02 16:24:11.151 Z, key: 1, value: {"ID": 1, "NAME": "sensor 1", "VALUE": 1100}, partition: 0
rowtime: 2026/04/02 16:24:11.194 Z, key: 2, value: {"ID": 2, "NAME": "sensor 2", "VALUE": 2000}, partition: 0
rowtime: 2026/04/02 17:09:22.582 Z, key: 2, value: {"ID": 2, "NAME": "sensor 2", "VALUE": 9999}, partition: 0
----

3. Create the Sink connectors.

We are going to create two sinks connections to mysql database:
----
+
* insert : insert all the readings in a table.
* upsert : update the last reading of each sensor.
+








+
[source,javascript]
----
curl -X PUT http://localhost:8083/connectors/sink-jdbc-mysql-01/config \
     -H "Content-Type: application/json" -d '{
    "connector.class"                    : "io.confluent.connect.jdbc.JdbcSinkConnector",
    "connection.url"                     : "jdbc:mysql://mysql:3306/demo",
    "topics"                             : "test01",
    "key.converter"                      : "org.apache.kafka.connect.storage.StringConverter",
    "value.converter"                    : "io.confluent.connect.avro.AvroConverter",
    "value.converter.schema.registry.url": "http://schema-registry:8081",
    "connection.user"                    : "connect_user",
    "connection.password"                : "asgard",
    "auto.create"                        : true,
    "auto.evolve"                        : true,
    "insert.mode"                        : "insert",
    "pk.mode"                            : "record_key",
    "pk.fields"                          : "MESSAGE_KEY"
}'
----
+
Things to customise for your environment:
+
* `topics` :  the source topic(s) you want to send to S3
* `key.converter` : match the serialisation of your source data (see https://www.confluent.io/blog/kafka-connect-deep-dive-converters-serialization-explained/[here])
* `value.converter` : match the serialisation of your source data (see https://www.confluent.io/blog/kafka-connect-deep-dive-converters-serialization-explained/[here])
+
Check data in target db
+
[source,bash]
----
docker exec -it mysql bash -c 'mysql -u root -p$MYSQL_ROOT_PASSWORD demo'
----
+
[source,sql]
----
mysql> SHOW TABLES;
+----------------+
| Tables_in_demo |
+----------------+
| test01         |
+----------------+
1 row in set (0.00 sec)

mysql> SELECT * FROM test01;
+------+------+-------------+
| COL1 | COL2 | MESSAGE_KEY |
+------+------+-------------+
|    1 | FOO  | X           |
|    2 | BAR  | Y           |
+------+------+-------------+
2 rows in set (0.00 sec)
----


4. Insert some more data. Notice what happens if you re-use a key. 
+
[source,sql]
----
INSERT INTO TEST01 (KEY_COL, COL1, COL2) VALUES ('Z',1,'WOO');
INSERT INTO TEST01 (KEY_COL, COL1, COL2) VALUES ('Y',4,'PFF');
----
+
The Kafka Connect tasks status shows that there's a duplicate key error
+
[source,bash]
----
$ curl -s http://localhost:8083/connectors/sink-jdbc-mysql-01/tasks/0/status | jq '.'
{
  "id": 0,
  "state": "FAILED",
  "worker_id": "kafka-connect:8083",
  "trace": "org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:614)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: Exception chain:\njava.sql.BatchUpdateException: Duplicate entry 'Y' for key 'test01.PRIMARY'\njava.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'Y' for key 'test01.PRIMARY'\n\n\tat io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:89)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)\n\t... 10 more\nCaused by: java.sql.SQLException: Exception chain:\njava.sql.BatchUpdateException: Duplicate entry 'Y' for key 'test01.PRIMARY'\njava.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'Y' for key 'test01.PRIMARY'\n\n\tat io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:86)\n\t... 11 more\n"
}
----

5. Update the Sink connector to use `UPSERT` mode
+
[source,javascript]
----
curl -X PUT http://localhost:8083/connectors/sink-jdbc-mysql-01/config \
     -H "Content-Type: application/json" -d '{
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "connection.url": "jdbc:mysql://mysql:3306/demo",
    "topics": "test01",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "connection.user": "connect_user",
    "connection.password": "asgard",
    "auto.create": true,
    "auto.evolve": true,
    "insert.mode": "upsert",
    "pk.mode": "record_key",
    "pk.fields": "MESSAGE_KEY"
}'
----
+
Now the row for key `Y` updates, whilst `Z` is added:
+
[source,sql]
----
mysql> SELECT * FROM test01;
+------+------+-------------+
| COL1 | COL2 | MESSAGE_KEY |
+------+------+-------------+
|    1 | FOO  | X           |
|    4 | PFF  | Y           |
|    1 | WOO  | Z           |
+------+------+-------------+
3 rows in set (0.00 sec)
----

6. Drop fields, add fields - note how the target schema evolves in-place
+
[source,javascript]
----
# Drop the existing connector
curl -X DELETE http://localhost:8083/connectors/sink-jdbc-mysql-01

# Create a new one, reading from the same topic with new config
# Because it's got a new name, the connector will re-read all the messages
# from the topic. 
curl -X PUT http://localhost:8083/connectors/sink-jdbc-mysql-02/config \
     -H "Content-Type: application/json" -d '{
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "connection.url": "jdbc:mysql://mysql:3306/demo",
    "topics": "test01",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "connection.user": "connect_user",
    "connection.password": "asgard",
    "auto.create": true,
    "auto.evolve": true,
    "insert.mode": "upsert",
    "pk.mode": "record_key",
    "pk.fields": "MESSAGE_KEY",
    "transforms": "dropSome,addSome",
    "transforms.dropSome.type": "org.apache.kafka.connect.transforms.ReplaceField$Value",
    "transforms.dropSome.blacklist": "COL2",
    "transforms.addSome.type":"org.apache.kafka.connect.transforms.InsertField$Value",
    "transforms.addSome.partition.field": "_partition",
    "transforms.addSome.timestamp.field" : "RECORD_TS"
}'
----
+
[source,sql]
----
mysql> describe test01;
+-------------+--------------+------+-----+---------+-------+
| Field       | Type         | Null | Key | Default | Extra |
+-------------+--------------+------+-----+---------+-------+
| COL1        | int          | YES  |     | NULL    |       |
| COL2        | varchar(256) | YES  |     | NULL    |       |
| MESSAGE_KEY | varchar(256) | NO   | PRI | NULL    |       |
| _partition  | int          | YES  |     | NULL    |       |
| RECORD_TS   | datetime(3)  | YES  |     | NULL    |       |
+-------------+--------------+------+-----+---------+-------+
5 rows in set (0.00 sec)

mysql> select * from test01;
+------+------+-------------+------------+-------------------------+
| COL1 | COL2 | MESSAGE_KEY | _partition | RECORD_TS               |
+------+------+-------------+------------+-------------------------+
|    1 | FOO  | X           |          0 | 2021-03-11 11:50:00.759 |
|    4 | PFF  | Y           |          0 | 2021-03-11 11:50:47.761 |
|    1 | WOO  | Z           |          0 | 2021-03-11 11:50:47.682 |
+------+------+-------------+------------+-------------------------+
3 rows in set (0.00 sec)
----


7. Write some CSV and JSON to new topics
+
[source,bash]
----
docker exec -i kafkacat kafkacat \
        -b broker:29092 -P \
        -t some_json_data <<EOF
{ "ID": 1, "Artist": "Rick Astley", "Song": "Never Gonna Give You Up" }        
{ "ID": 2, "Artist": "asdfasd", "Song": "dsfjfghg" }        
EOF

docker exec -i kafkacat kafkacat \
        -b broker:29092 -P \
        -t some_json_data_with_a_schema <<EOF
{ "schema": { "type": "struct", "optional": false, "version": 1, "fields": [ { "field": "ID", "type": "string", "optional": true }, { "field": "Artist", "type": "string", "optional": true }, { "field": "Song", "type": "string", "optional": true } ] }, "payload": { "ID": "1", "Artist": "Rick Astley", "Song": "Never Gonna Give You Up" } }
EOF

docker exec -i kafkacat kafkacat \
        -b broker:29092 -P \
        -t some_csv_data <<EOF
1,Rick Astley,Never Gonna Give You Up
EOF
----

8. Stream the JSON data that has a schema to DB: 
+
[source,bash]
----
curl -X PUT http://localhost:8083/connectors/sink-jdbc-mysql-02-json/config \
     -H "Content-Type: application/json" -d '{
    "connector.class"               : "io.confluent.connect.jdbc.JdbcSinkConnector",
    "connection.url"                : "jdbc:mysql://mysql:3306/demo",
    "topics"                        : "some_json_data_with_a_schema",
    "key.converter"                 : "org.apache.kafka.connect.storage.StringConverter",
    "value.converter"               : "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "true",
    "connection.user"               : "connect_user",
    "connection.password"           : "asgard",
    "auto.create"                   : true,
    "auto.evolve"                   : true,
    "insert.mode"                   : "insert"
}'
----

9. Use ksqlDB to apply a schema to the CSV and schemaless-JSON, and show off `INSERT INTO` for merging two topics into one with a common schema
+
[source,sql]
----
CREATE STREAM SOME_JSON (ID INT, ARTIST VARCHAR, SONG VARCHAR) 
  WITH (KAFKA_TOPIC='some_json_data', VALUE_FORMAT='JSON');

SET 'auto.offset.reset' = 'earliest';

CREATE STREAM SOME_JSON_AS_AVRO 
  WITH (VALUE_FORMAT='AVRO') AS 
    SELECT * FROM SOME_JSON;

CREATE STREAM SOME_CSV (ID INT, ARTIST VARCHAR, SONG VARCHAR) 
  WITH (KAFKA_TOPIC='some_csv_data', VALUE_FORMAT='DELIMITED');

INSERT INTO SOME_JSON_AS_AVRO SELECT * FROM SOME_CSV;
----

10. Create a sink for the reserialized data
+
[source,bash]
----
curl -X PUT http://localhost:8083/connectors/sink-jdbc-mysql-02-avro/config \
     -H "Content-Type: application/json" -d '{
    "connector.class"                    : "io.confluent.connect.jdbc.JdbcSinkConnector",
    "connection.url"                     : "jdbc:mysql://mysql:3306/demo",
    "topics"                             : "SOME_JSON_AS_AVRO",
    "key.converter"                      : "org.apache.kafka.connect.storage.StringConverter",
    "value.converter"                    : "io.confluent.connect.avro.AvroConverter",
    "value.converter.schema.registry.url": "http://schema-registry:8081",
    "connection.user"                    : "connect_user",
    "connection.password"                : "asgard",
    "auto.create"                        : true,
    "auto.evolve"                        : true,
    "insert.mode"                        : "insert"
}'
----

'''

References

* https://rmoff.dev/crunch19-zero-to-hero-kafka-connect[From Zero to Hero with Kafka Connect]
* https://hub.confluent.io[Confluent Hub]
* https://docs.confluent.io/current/connect/kafka-connect-jdbc/sink-connector/index.html[JDBC Sink connector docs]
* https://rmoff.net/2019/10/15/skipping-bad-records-with-the-kafka-connect-jdbc-sink-connector/[Skipping bad records with the Kafka Connect JDBC sink connector]
* https://www.confluent.io/blog/simplest-useful-kafka-connect-data-pipeline-world-thereabouts-part-3/[Single Message Transform blog]
* https://docs.confluent.io/current/connect/transforms/insertfield.html[InsertField] Single Message Transform
