This uses Docker Compose to run the Kafka Connect worker.

1. Execute start.bat
+
[source,bash]
----
start.bat
----
+
[source,bash]
----
@echo off
echo wait until ksqldb ready...
rem build and deply
docker compose up -d --build
setlocal enabledelayedexpansion
rem wait until kafka server is ready
rem wait until ksqldb is ready
for /l %%i in (1,1,90) do (
    set "status="
    for /f "delims=" %%a in ('curl --http1.1 -s http://localhost:8088/info' ) do (
        set line=%%a
        rem echo this is line !line!
    )
    for /f "tokens=2 delims=:" %%a in ("!line:*serverStatus=!") do (
        set "tmp=%%a"
    )
    rem echo status !tmp!
    set "tmp=!tmp:"=!"
    set "tmp=!tmp:,=!"
    set "tmp=!tmp:}=!"
    set "tmp=!tmp: =!"
    echo status-!tmp!-
    if /i "!tmp!"=="RUNNING" (
        echo Server Running:  !line!
        goto :end
    )
    timeout /t 2 > nul
)
echo wait until topics ready...
:end 
rem Init ksqldb
echo wait until topics ready...
docker exec -it ksqldb-server /bin/ksql --file /home/appuser/init-sql/init.sql
----


2. Make sure everything is up and running
+
[source,bash]
----
➜ docker ps --format '{{.Names}}  {{.Image}}  {{.Status}}'
----
+
[source,bash]
----
ksqldb-cli  confluentinc/ksqldb-cli:0.29.0  Up 4 hours
ksqldb-server  simple_kafka-ksqldb-server  Up 4 hours
schema-registry  confluentinc/cp-schema-registry:7.8.0  Up 4 hours
kafka-broker  confluentinc/cp-kafka:latest  Up 4 hours
simple_kafka-phpmyadmin-1  phpmyadmin  Up 4 hours
zookeeper  confluentinc/cp-zookeeper:latest  Up 4 hours
kafka-ui  provectuslabs/kafka-ui  Up 4 hours
simple_kafka-mysql-1  simple_kafka-mysql  Up 4 hours
----

3. Create test topics + data using ksqlDB (but it's still just a Kafka topic under the covers)

Enter in KSQLDB CLI:
+
[source,bash]
----
docker exec -it ksqldb-server ksql http://ksqldb:8088
----
Or you can enter in the container via docker desktop and type "ksql".

+
[source,sql]
----
CREATE STREAM dim_sensores (KEY_COL VARCHAR KEY, id_sensor INT, nombre_sensor VARCHAR)
  WITH (KAFKA_TOPIC='dim_sensores', PARTITIONS=1, VALUE_FORMAT='AVRO');
----

[source,sql]
----
INSERT INTO dim_sensores (KEY_COL, id_sensor, nombre_sensor) VALUES ('X',1,'sensor 1');
INSERT INTO dim_sensores (KEY_COL, id_sensor, nombre_sensor) VALUES ('Y',2,'sensor 2');
----

[source,sql]
----
SHOW TOPICS;
PRINT dim_sensores FROM BEGINNING LIMIT 2;
----

[source,sql]
----
Key format: KAFKA_STRING
Value format: AVRO or KAFKA_STRING
rowtime: 2026/04/02 16:16:35.392 Z, key: X, value: {"ID_SENSOR": 1, "NOMBRE_SENSOR": "sensor 1"}, partition: 0
rowtime: 2026/04/02 16:16:35.441 Z, key: Y, value: {"ID_SENSOR": 2, "NOMBRE_SENSOR": "sensor 2"}, partition: 0
Topic printing ceased
----

Now topic of readings:

[source,sql]
----
CREATE STREAM readings (KEY_COL VARCHAR KEY, id_sensor INT, value INT)
  WITH (KAFKA_TOPIC='readings', PARTITIONS=1, VALUE_FORMAT='AVRO');
----

[source,sql]
---
INSERT INTO readings (KEY_COL, id_sensor, value) VALUES ('X',1,1100);
INSERT INTO readings (KEY_COL, id_sensor, value) VALUES ('Y',2,2000);
----

[source,sql]
----
SHOW TOPICS;
PRINT readings FROM BEGINNING LIMIT 2;
----

[source,sql]
----
Key format: KAFKA_STRING
Value format: AVRO
rowtime: 2026/04/02 16:24:11.151 Z, key: X, value: {"ID_SENSOR": 1, "VALUE": 1100}, partition: 0
rowtime: 2026/04/02 16:24:11.194 Z, key: Y, value: {"ID_SENSOR": 2, "VALUE": 2000}, partition: 0
Topic printing ceased
----

Now a topic joinning de readings with dim_sensors:

First, make a test:

[source,sql]
----
SELECT
    T0.id_sensor ROWKEY, -- KEY
    T1.id_sensor as id,
    T1.nombre_sensor as name,
    T0.value as value
    FROM readings T0
    INNER JOIN dim_sensores T1 WITHIN 3 DAYS
    ON T0.id_sensor = T1.id_sensor
EMIT CHANGES;
----

[source,bash]
----
+------------------+------------------+------------------+------------------+
|ROWKEY            |ID                |NAME              |VALUE             |
+------------------+------------------+------------------+------------------+
|1                 |1                 |sensor 1          |1100              |
|2                 |2                 |sensor 2          |2000              |
----

Evething ok?, create new stream/topic enrich

[source,sql]
----
CREATE STREAM IF NOT EXISTS reading_enrich WITH (KAFKA_TOPIC='reading_enrich', PARTITIONS=1, REPLICAS=1, VALUE_FORMAT='AVRO') 
AS SELECT
    T0.id_sensor ROWKEY, -- KEY
    T1.id_sensor as id,
    T1.nombre_sensor as name,
    T0.value as value
    FROM readings T0
    INNER JOIN dim_sensores T1 WITHIN 3 DAYS
    ON T0.id_sensor = T1.id_sensor
;
----

Check new Topic:
[source,sql]
----
SHOW TOPICS;
PRINT reading_enrich FROM BEGINNING LIMIT 2;
----

[source,sql]
----
Key format: KAFKA_INT or KAFKA_STRING
Value format: AVRO
rowtime: 2026/04/02 16:24:11.151 Z, key: 1, value: {"ID": 1, "NAME": "sensor 1", "VALUE": 1100}, partition: 0
rowtime: 2026/04/02 16:24:11.194 Z, key: 2, value: {"ID": 2, "NAME": "sensor 2", "VALUE": 2000}, partition: 0
Topic printing ceased
----

Try with a new incoming reading from sensor 2.

[source,sql]
----
INSERT INTO readings (KEY_COL, id_sensor, value) VALUES ('4',2,9999);
----

[source,sql]
----
PRINT reading_enrich FROM BEGINNING LIMIT 10;
----

[source,sql]
----
Key format: KAFKA_INT or KAFKA_STRING
Value format: AVRO
rowtime: 2026/04/02 16:24:11.151 Z, key: 1, value: {"ID": 1, "NAME": "sensor 1", "VALUE": 1100}, partition: 0
rowtime: 2026/04/02 16:24:11.194 Z, key: 2, value: {"ID": 2, "NAME": "sensor 2", "VALUE": 2000}, partition: 0
rowtime: 2026/04/02 17:09:22.582 Z, key: 2, value: {"ID": 2, "NAME": "sensor 2", "VALUE": 9999}, partition: 0
----

3. Create the Sink connectors.

We are going to create two sinks connections to mysql database:

`insert` : insert all the readings in a table

`upsert`: update the last reading of each sensor

Here some commads:
[source,sql]
----
SHOW | LIST [SOURCE | SINK] CONNECTORS;
DROP CONNECTOR [IF EXISTS] "connector_name";
DESCRIBE CONNECTOR "connector_name";
----

[source,sql]
----
CREATE SINK CONNECTOR IF NOT EXISTS "mysql-insert-sink"  WITH (
    "task.max"='1',
    "connection.url"= 'jdbc:mysql://mysql:3306/temp_db',
    "connection.user"= 'myuser',
    "connection.password"= 'mypassword',
    "topics"= 'reading_enrich',
    "connector.class"= 'io.confluent.connect.jdbc.JdbcSinkConnector',
    "key.converter"='org.apache.kafka.connect.storage.StringConverter',
    "value.converter"='io.confluent.connect.avro.AvroConverter',
    "value.converter.schema.registry.url"='http://schema-registry:8081',
    "table.name.format"= 'kafka_${topic}',
    "auto.create"= 'true',
    "auto.evolve"= 'true',
    "insert.mode"= 'insert',
    -- Añade o quita columnas 
    "transforms"= 'dropSome,addSome',
    "transforms.dropSome.type"='org.apache.kafka.connect.transforms.ReplaceField$Value',
    --"transforms.dropSome.blacklist"= 'COL2',
    "transforms.addSome.type"='org.apache.kafka.connect.transforms.InsertField$Value',
    "transforms.addSome.partition.field"= '_partition',
    "transforms.addSome.timestamp.field"= '_record_TS_UTC'
    -- add static values column:
    "transforms.addSome.static.field"= 'source',
    "transforms.addSome.static.value"= 'reading_enrich'
);
----

And upsert sink type:

[source,sql]
----
CREATE SINK CONNECTOR IF NOT EXISTS "mysql-upsertA-sink"  WITH (
    "task.max"='1',
    "connection.url"= 'jdbc:mysql://mysql:3306/temp_db',
    "connection.user"= 'myuser',
    "connection.password"= 'mypassword',
    "topics"= 'reading_enrich',
    "connector.class"= 'io.confluent.connect.jdbc.JdbcSinkConnector',
    "key.converter"='org.apache.kafka.connect.storage.StringConverter',
    "value.converter"='io.confluent.connect.avro.AvroConverter',
    "value.converter.schema.registry.url"='http://schema-registry:8081',
    "table.name.format"= 'kafka_upsertA_${topic}',
    "auto.create"= 'true',
    "auto.evolve"= 'true',
    -- set index 
    "insert.mode"= 'upsert',
    "pk.mode"='record_value',
    "pk.fields"='ID', 
    -- Añade o quita columnas 
    "transforms"= 'dropSome,addSome',
    "transforms.dropSome.type"='org.apache.kafka.connect.transforms.ReplaceField$Value',
    --"transforms.dropSome.blacklist"= 'COL2',
    "transforms.addSome.type"='org.apache.kafka.connect.transforms.InsertField$Value',
    "transforms.addSome.partition.field"= '_partition',
    "transforms.addSome.timestamp.field"= 'RECORD_TS',
    -- add static values column:
    "transforms.addSome.static.field"= 'source',
    "transforms.addSome.static.value"= 'reading_enrich'
);
----

NOTE:
- Name of columns are case sensitive. 

Things to customise for your environment:

`topics` :  the source topic(s) you want to send

`key.converter` : match the serialisation of your source data (see https://www.confluent.io/blog/kafka-connect-deep-dive-converters-serialization-explained/[here])

`value.converter` : match the serialisation of your source data (see https://www.confluent.io/blog/kafka-connect-deep-dive-converters-serialization-explained/[here])

`insert.mode` : insert or upsert.

`pk.mode` : record_value (use the value) or record_key (use the key)

`pk.fields` : columns (could be various) to use as index. Is case sensitive!.

`transforms` : use transforms to add or delete columns


'''

References

* https://rmoff.dev/crunch19-zero-to-hero-kafka-connect[From Zero to Hero with Kafka Connect]
* https://hub.confluent.io[Confluent Hub]
* https://docs.confluent.io/current/connect/kafka-connect-jdbc/sink-connector/index.html[JDBC Sink connector docs]
* https://rmoff.net/2019/10/15/skipping-bad-records-with-the-kafka-connect-jdbc-sink-connector/[Skipping bad records with the Kafka Connect JDBC sink connector]
* https://www.confluent.io/blog/simplest-useful-kafka-connect-data-pipeline-world-thereabouts-part-3/[Single Message Transform blog]
* https://docs.confluent.io/current/connect/transforms/insertfield.html[InsertField] Single Message Transform
