CREATE DATABASE IF NOT EXIsTS `temp_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE  `temp_db`;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `temp_table` (
  `uuid` varchar(36) NOT NULL,
  `registered` date DEFAULT (CURRENT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE EVENT insertion_event
-- ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 MINUTE
ON SCHEDULE EVERY 1 MINUTE STARTS CURRENT_TIMESTAMP
DO INSERT INTO temp_table (uuid) VALUES ('Evento 1');

-- SET GLOBAL event_scheduler = ON;
-- SHOW EVENTS FROM your_database_name;
--ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 MINUTE

COMMIT;